Update expanded registers
ETC-A/etca-spec pull request #21
Opened 2022-07-06 16:59 UTC by Ezra

Resolves #20 and makes some stylistic edits to the surrounding text.

2022-07-06 17:17 UTC, EnderShadow requested changes
I prefer that we stick with "caller saved" and "callee saved" since that has a technical meaning whereas "call-clobbered" and "call-preserved" don't have the same meaning.

2022-07-06 17:19 UTC, JKTKops commented
Indeed, caller saved and callee saved are technical terms. The confusion is unfortunate but they are standard now.

2022-07-06 17:25 UTC, JKTKops requested changes

2022-07-06 17:25 UTC, JKTKops commented on extensions/stack-and-functions/README.md
> +- ln is the link register and stores the address that this function should return to. This is hard coded into the call and return instructions.
```suggestion
- ln is the link register and stores the address that this function should return to. This is hardcoded into the call and return instructions.
```

2022-07-06 17:25 UTC, JKTKops commented on extensions/stack-and-functions/README.md
> +| `r7`     | `ln`      | call-clobbered |
```suggestion
| Register | Alias     | Calling Convention |
|----------|-----------|----------------|
| `r0`     | `a0`/`v0` | caller saved |
| `r1`     | `a1`/`v1` | caller saved |
| `r2`     | `a2`      | caller saved |
| `r3`     | `s0`      | callee saved |
| `r4`     | `s1`      | callee saved |
| `r5`     | `bp`      | callee saved |
| `r6`     | `sp`      | callee saved |
| `r7`     | `ln`      | caller saved |
```
Capitalization doesn't matter much to me. They were capitalized before but leaving them lowercase is fine.

2022-07-06 17:25 UTC, JKTKops commented on extensions/expanded-registers/README.md
> +| `r15`    | `s4`  | call-preserved |
Same as suggested change below; use technical terms.

2022-07-06 17:25 UTC, JKTKops commented on extensions/expanded-registers/README.md
> +|:-------|-----|-----|-----|-----|
Cleaning these up is fine, but remember that markdown doesn't actually care about the spacing and spacing things "correctly" gets messed up if the table is ever modified. This has come up in our tables before.

2022-07-14 23:43 UTC, EnderShadow commented
As this has been idle for a bit, I'm closing it and putting the changes in #24

2022-07-14 23:43 UTC, closed without merging